#dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
os:
  - linux
  - osx

language: r
sudo: false
r: 3.6.3

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - graphviz

# Install packrat if needed and have it restore packages.

use_bioc: true
bioc_required: true

bioc_packages:
  - Gviz
  - Homo.sapiens
  - OrganismDbi
  - Rsamtools
  - TxDb.Hsapiens.UCSC.hg19.knownGene
  - TxDb.Hsapiens.UCSC.hg38.knownGene
  - BSgenome.Hsapiens.UCSC.hg19
  - BSgenome.Hsapiens.UCSC.hg38
  - EnsDb.Hsapiens.v75
  - EnsDb.Hsapiens.v86
  
cache:
  # Main R library
  packages: true
  directories:

    # PhantomJS
    - travis_phantomjs

# Install PhantomJS (if not cached)
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphviz; fi
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "hash -r"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
  - "phantomjs --version"

script:
  - Rscript make_bam.R
  - R -f run_tests.R
