app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$uploadFile(gene1 = "mygene.txt",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(pileup = "click")
app$snapshot()
app$setInputs(Gene_name = "POLG",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(tabSet = "UCSC gene",wait_=FALSE, values_=FALSE)
app$setInputs(button1 = "click",timeout_=1000000)
app$snapshot()
app$setInputs(Chromosome = "chr15",wait_=FALSE, values_=FALSE)
app$setInputs(coverage_co = "32",wait_=FALSE, values_=FALSE)
app$setInputs(Sample = "1",wait_=FALSE, values_=FALSE)
app$setInputs(transcript_id = "1",wait_=FALSE, values_=FALSE)
app$setInputs(exon_number = "10", timeout_=1000000)
app$setInputs(tabSet = "UCSC exons",wait_=FALSE, values_=FALSE)
Sys.sleep(30)
app$snapshot()
app$setInputs(tabSet = "Gene coverage",wait_=FALSE, values_=FALSE)
Sys.sleep(180)
app$snapshot()
